### ISSUE TITLE
how to load module after build?

### ISSUE THREAD

**Issue by igroykt** [FarhansCode/rtl8188ee#1]
Hi, @FarhansCode !
I'm new on freebsd and i need to install rtl8188ee driver.
Tried ndis with no luck then i found this repo.
hardware: lenovo q190
pciconf output: 'RTL8188EE Wireless Network Adapter'
uname: FreeBSD riko 12.0-CURRENT FreeBSD 12.0-CURRENT #1 76e250ce6(master): Tue Mar  7 19:52:13 YAKT 2017     root@riko:/usr/obj/usr/home/igro/distr/rtl8188ee/sys/MYKERNEL  amd64
Builded without errors but i don't see any new interface in ifconfig (even after reboot).
I thought "make reinstallkernel" will reinstall rebuilded kernel and after reboot wireless interface will be recognized automatically.

**Comment by FarhansCode** [comment]
unfortunately, this driver does not work native with FreeBSD yet. I am
currently working on it.

--
Farhan Khan
PGP Fingerprint: 782F 342B 5B08 0D2F F4E8 82C3 FFA1 CAE1 6536 51CA

**Comment by igroykt** [comment]
ok
